# Site settings
title: Питон и КИЛИ

baseurl: ""
url: https://pykili.github.io # the base hostname & protocol for your site
git_address: https://github.com/pykili/pykili.github.io
git_edit_address: https://github.com/pykili/pykili.github.io/blob/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
timezone: Europe/Moscow
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
